// <auto-generated />
namespace Learn_ASP.NET.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class DemoUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DemoUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201910120303386_DemoUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
