// <auto-generated />
namespace Learn_ASP.NET.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class a_1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(a_1));
        
        string IMigrationMetadata.Id
        {
            get { return "201910100951209_a_1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
